//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLNIY_TRESH_PROISHODIT_NIKTO_NICHEGO_NE_PONIMAET
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineCourses
    {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> SubjectID { get; set; }
    
        public virtual Subjects Subjects { get; set; }
    }
}
